# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data_import.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='data_import.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11\x64\x61ta_import.proto\"R\n\x1dimport_s2_video_learningVideo\x12\x31\n\x03row\x18\x01 \x03(\x0b\x32$.import_s2_video_learningVideo_tuple\"\xbd\x02\n#import_s2_video_learningVideo_tuple\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\ncreated_at\x18\x02 \x01(\t\x12\x12\n\nupdated_at\x18\x03 \x01(\t\x12\x0c\n\x04uuid\x18\x04 \x01(\t\x12\x0b\n\x03url\x18\x05 \x01(\t\x12\x0c\n\x04name\x18\x06 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x07 \x01(\t\x12\r\n\x05image\x18\x08 \x01(\t\x12\x0e\n\x06number\x18\t \x01(\t\x12\x14\n\x0c\x64uration_min\x18\n \x01(\t\x12\x12\n\nis_popular\x18\x0b \x01(\t\x12\x10\n\x08\x63lass_id\x18\x0c \x01(\t\x12\x12\n\nsubject_id\x18\r \x01(\t\x12\x11\n\taccess_id\x18\x0e \x01(\t\x12\x12\n\nsfTableoid\x18\x0f \x01(\t\x12\x0e\n\x06sfXmin\x18\x10 \x01(\tb\x06proto3'
)




_IMPORT_S2_VIDEO_LEARNINGVIDEO = _descriptor.Descriptor(
  name='import_s2_video_learningVideo',
  full_name='import_s2_video_learningVideo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='row', full_name='import_s2_video_learningVideo.row', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=103,
)


_IMPORT_S2_VIDEO_LEARNINGVIDEO_TUPLE = _descriptor.Descriptor(
  name='import_s2_video_learningVideo_tuple',
  full_name='import_s2_video_learningVideo_tuple',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='import_s2_video_learningVideo_tuple.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='created_at', full_name='import_s2_video_learningVideo_tuple.created_at', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='updated_at', full_name='import_s2_video_learningVideo_tuple.updated_at', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='uuid', full_name='import_s2_video_learningVideo_tuple.uuid', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='url', full_name='import_s2_video_learningVideo_tuple.url', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='import_s2_video_learningVideo_tuple.name', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='description', full_name='import_s2_video_learningVideo_tuple.description', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='image', full_name='import_s2_video_learningVideo_tuple.image', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='number', full_name='import_s2_video_learningVideo_tuple.number', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='duration_min', full_name='import_s2_video_learningVideo_tuple.duration_min', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_popular', full_name='import_s2_video_learningVideo_tuple.is_popular', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='class_id', full_name='import_s2_video_learningVideo_tuple.class_id', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='subject_id', full_name='import_s2_video_learningVideo_tuple.subject_id', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='access_id', full_name='import_s2_video_learningVideo_tuple.access_id', index=13,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sfTableoid', full_name='import_s2_video_learningVideo_tuple.sfTableoid', index=14,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sfXmin', full_name='import_s2_video_learningVideo_tuple.sfXmin', index=15,
      number=16, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=106,
  serialized_end=423,
)

_IMPORT_S2_VIDEO_LEARNINGVIDEO.fields_by_name['row'].message_type = _IMPORT_S2_VIDEO_LEARNINGVIDEO_TUPLE
DESCRIPTOR.message_types_by_name['import_s2_video_learningVideo'] = _IMPORT_S2_VIDEO_LEARNINGVIDEO
DESCRIPTOR.message_types_by_name['import_s2_video_learningVideo_tuple'] = _IMPORT_S2_VIDEO_LEARNINGVIDEO_TUPLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

import_s2_video_learningVideo = _reflection.GeneratedProtocolMessageType('import_s2_video_learningVideo', (_message.Message,), {
  'DESCRIPTOR' : _IMPORT_S2_VIDEO_LEARNINGVIDEO,
  '__module__' : 'data_import_pb2'
  # @@protoc_insertion_point(class_scope:import_s2_video_learningVideo)
  })
_sym_db.RegisterMessage(import_s2_video_learningVideo)

import_s2_video_learningVideo_tuple = _reflection.GeneratedProtocolMessageType('import_s2_video_learningVideo_tuple', (_message.Message,), {
  'DESCRIPTOR' : _IMPORT_S2_VIDEO_LEARNINGVIDEO_TUPLE,
  '__module__' : 'data_import_pb2'
  # @@protoc_insertion_point(class_scope:import_s2_video_learningVideo_tuple)
  })
_sym_db.RegisterMessage(import_s2_video_learningVideo_tuple)


# @@protoc_insertion_point(module_scope)
