SELECT top 100 [id]
      ,[telegram_messages_types__id]
  FROM [dbo].[telegram_messages]
  SELECT [id]
      ,[recipient_telegram__id]
      ,[telegram_messages_types__id]
      ,[created_by]
      ,[modified_by]
  FROM [dbo].[telegram_messages]